[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "fb77fb1af1a3733d8bd27e734f6e2e8e5c24bc4f"
os = "macos"

    [[ngspice.download]]
    sha256 = "2966942bab87e019a48bc9b40f843b1063bd4231f2fbc958dcddf7caafd31cc6"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.aarch64-apple-darwin.tar.gz"
[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "db4e4965c17e0c5e1841d3195ba196ed1fc6dfa2"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "ab7713f45ed9d93593ad308a87bdf1ebf8252865554e966d5e3f90a75e183829"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.aarch64-linux-gnu.tar.gz"
[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "f1b0b13084ce43e5ccf09f24505e0c740a8ab331"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "8e5bd8c43c16bc39df95772c5844ec129b919e8486288ce85ee38f16be795f87"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.aarch64-linux-musl.tar.gz"
[[ngspice]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7098ec035d685c0d4f375cf42b68f6f724ef8c43"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "d541074ee71b2c6421ae55401f71cfd283b982f4d13cca9a8e09949d1134d898"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.armv6l-linux-gnueabihf.tar.gz"
[[ngspice]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "abf2bf435e2b42db319b90e02e73703107f9d2d8"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "312db65c567c0d7e39c76e8539af81f248568cb18c850674cce59277a22041c0"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.armv6l-linux-musleabihf.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e5fbd2277cdc8151f818766828da56e73f1f7a1"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "e099cd839cacef009c9292692d16c62a2386348697242098490fb76632026793"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "60832228e9332d82894a3351fabe925d79d42f8c"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "608bb4c696f86eced8924a8c3ef54fde83a8878a08a8c50a957d068ae858f04d"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.armv7l-linux-musleabihf.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "ce78413af040b490797d3a7b55013f1fdad43cc3"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "946142bb254aac372257bca6faffc76407dccc8efde1923e56728172412b0cae"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.i686-linux-gnu.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "b29d78da8e8195fcfbbaf3af6de719e4cd754d0d"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "5153a94b117b074b5106b7e5cf7c4ae585a1874da17f58e94603a629a1dc7ca6"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.i686-linux-musl.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "6ad6475e38ffca429c39150b390b75333b5c53ec"
os = "windows"

    [[ngspice.download]]
    sha256 = "fb5a4a2429b0cced5e18ee507ac1eec3cecd9f8abf1306bd085f29799dbaf60b"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.i686-w64-mingw32.tar.gz"
[[ngspice]]
arch = "powerpc64le"
git-tree-sha1 = "7e7344effed57dd14ceee2d71a5b17bc6cdae9f6"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "8519c6526a7ca78091162d635d71722cbcdb9841d1dbf4af0f47da88407f2bec"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.powerpc64le-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "e24e0821d5f0aaca2335ddae98d60a95812bda14"
os = "macos"

    [[ngspice.download]]
    sha256 = "75f0c00eca6399dcf5b98a63ad8b82af1ceebc9b6ff2695d4f95bb7a547aacf0"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.x86_64-apple-darwin.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "bcebfdd765ba12215d917b24d07fcb681f742945"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "5ae38e31422a2150f6231e54f666619a3753bf5c6ffd5c54737a24c6a96e6054"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.x86_64-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "c8f4277c20482d7b53dc7b182d27533e957f1f9e"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "29d6506067f06107f9ea55be49fd2ae93dae3cdae4b8e08605b157c0ee35b4a7"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.x86_64-linux-musl.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "6d6bb885722d1cafeea2fb4f1772db7f169dd804"
os = "freebsd"

    [[ngspice.download]]
    sha256 = "821db2e3dc168dc3cdf75c55f4d9fa44bfe3fe4f50e33ef8add353597bf760ab"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.x86_64-unknown-freebsd.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "957040140c16e137b8f8efc4b5e7e61f1a2ee6a2"
os = "windows"

    [[ngspice.download]]
    sha256 = "2291d9a6ef234af6a750fcd6b068c28a54c2c6e77544b0acde007bd419f4980f"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v41.0.0+0/ngspice.v41.0.0.x86_64-w64-mingw32.tar.gz"
