[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "cd3ccd28b82b9b35617f8928dcd88eac7248b777"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "9097b1e6f4acde80025a457cedfaf484f1a04fe895044c26790eee7e22741d8c"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.aarch64-linux-gnu.tar.gz"
[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "9a50f95cc19c579d1aad57715f2c4f41c59290ea"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "2dc6402a0b36e6e6de51c5904ad223f8b5ce4bf6039b6e2f735d47ef99cf707c"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.aarch64-linux-musl.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5bf69dbb08651eda86984eaabc4ffa2e10325f7"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "2a3972bcb7baff126e800ce9ad395f37480ef8a6c7184433a94d03af80ae7662"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b5bdfced3bbeff7ba0c15ff0b83c4e4204bd889"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "d56caf93d5e96cf0b92f389a0857bc108784090f0190ea11043fa0280f66f661"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.armv7l-linux-musleabihf.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "846c19a5752489c66fd7a22567d035debff4cfdb"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "6f7b0446298e4d6116a62465bbf00d18050d1e7faf05a367c2ae0d73e1803b6e"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.i686-linux-gnu.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "95f87a05214efa776d281998f9a288e6bfcdbb03"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "a6ca5df94455a8f936c282f071fe9fb2aeb83c491962f26383aaf645fc7e6337"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.i686-linux-musl.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "4c294679de4503baff431d26fb5423d4ac6b3742"
os = "windows"

    [[ngspice.download]]
    sha256 = "740d9bff0b4b8ed82de7902d63728832468a9b86513722b14c72afc998deb7bb"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.i686-w64-mingw32.tar.gz"
[[ngspice]]
arch = "powerpc64le"
git-tree-sha1 = "2f42dd946352713685b648ee46b0ad905014548d"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "b81a535a402d0eed43c77a1dd1ac2fb8ed85cf4811733b0b131f62a34cf53169"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.powerpc64le-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "bfa962be48e90da1738f1c830f8558af8846f5a6"
os = "macos"

    [[ngspice.download]]
    sha256 = "4e415c502028c65a54c5872e2c336e400d987131b9295bfa215493dd8ca0942d"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.x86_64-apple-darwin.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "c040af52c1505ff5655a04441567c2435d0ea4c8"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "91298a8a5a557c254aa79864025d976a3bb96a30f8dad9c72dd66ca18ffb3fbf"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.x86_64-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "d57b22d73762b6ad2778f7ed9171601897b9c7b0"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "63a87a28e2cc685121c90dd1ab447040ec6471e49dedd3c8ad5b5cd9df9f4ac1"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.x86_64-linux-musl.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "7af119ee9fc56fa24353861f65f143e8a51393b8"
os = "freebsd"

    [[ngspice.download]]
    sha256 = "020e6354b0d3d0c635c6ec80338716282fd88095fb7261da9b0658eed6bcbc20"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.x86_64-unknown-freebsd.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "1bfee081c26f24a581851e1fb275695cd25ca5bb"
os = "windows"

    [[ngspice.download]]
    sha256 = "4a056454b8cc71c838cfb20323b0f3b1e7e6d6374ac078015c163bf130e61e3d"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+0/ngspice.v34.0.0.x86_64-w64-mingw32.tar.gz"
