[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "b9d83476ad7a360eab68a8aeb22f8bbca84bb4e6"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "23056d1f61bda3b7df0cf86832a3d79ffa937e17c5793663e73b7ec2ef0de900"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.aarch64-linux-gnu.tar.gz"
[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "3353fca16d210f2bf4c7623aca48a5d351eee165"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "ddf177e418b6b876667335d1b047fd1282e02d3471703b4822be60ff3886f6e3"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.aarch64-linux-musl.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d36ec5a41d8d13e7c6d6bc8d1861b42e6cb4d74"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "3adbbfdc766a5027ef52de93a4fd0a35ceddb1520b677553f9ed71fd7e0cdae4"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0a8365f142883b29a8517de4003f4e8eec99fd8a"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "80f9c210e820a884470375eed1d3bd61e12b8ad4929f8a13a8c0a30f56a7b458"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.armv7l-linux-musleabihf.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "fa3895c62ecb652dabbf9614514a9f24034caf28"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "5964b568fb112bf473b33566429d7a7ed6787f614d33f9a722981e0b45ee3bcf"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.i686-linux-gnu.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "e227b16c30558cf8b919ce0b73d92e0c8a580357"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "4f3c318d7bacc89bae5976cfb9533c13d980051460e487a118d97094582be157"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.i686-linux-musl.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "dc68a7fef53a07724930983f6e42faadfbdca1d1"
os = "windows"

    [[ngspice.download]]
    sha256 = "44610f84931364ee61077d558b530fd94a2a8c92e0408e9cf5c13300bc154e1b"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.i686-w64-mingw32.tar.gz"
[[ngspice]]
arch = "powerpc64le"
git-tree-sha1 = "a80d1dae95e5dd5810994bc97ac12fa1950e0b43"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "63a96c98f0d303f6c893ff1ca228790bc14fbd49fae345dbd7a4136e33eaf085"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.powerpc64le-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "9fe86fb4a2f6a621d892244295ad293b227868a6"
os = "macos"

    [[ngspice.download]]
    sha256 = "c2176cdff5d276e2b1deeaf8d31b7f55d7d725a3fc40e3f17f7309df2c93d68e"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.x86_64-apple-darwin.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "55666133d67ec9512409f36a9350f8bcbbb20419"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "e58370fcbe162a2953f63896b7c3eda90677e71bfd47f50dc9333fb2b8d4ce6a"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.x86_64-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "785b3dbd58c5d34a9a9653aeefc53b59851d7f65"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "e18a9f64c37cb8177d3df0d7c36b4721cc60010bce62c02af0e64a6bfcc53252"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.x86_64-linux-musl.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "76c9046aa02d56a334bfb6dc6a9c58432b54b7ba"
os = "freebsd"

    [[ngspice.download]]
    sha256 = "475200b03f85653d0517efb778b94f8fae1f4f93ca10c306868198ce55d37432"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.x86_64-unknown-freebsd.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "cfec4ef3cd0a38a72621f3dbfcab27d7c4a7bc70"
os = "windows"

    [[ngspice.download]]
    sha256 = "ac81c31def2da7101504481089d39665990a0031a4c620a9a65375b925dec31f"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v34.0.0+1/ngspice.v34.0.0.x86_64-w64-mingw32.tar.gz"
