[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "ee5fea72dc4a2d33c6441b728a979e1d4b4843dd"
os = "macos"

    [[ngspice.download]]
    sha256 = "461f2fbae16885530ceb49f6eebb5a2c76b2c619e651fe02d49e422471e52655"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.aarch64-apple-darwin.tar.gz"
[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "d9cae033c631c4b8fa38b3abcfabb694cb721262"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "ad12e61d1f359c2060768e1d1693bda200a185a8452033380ba38e70988e5838"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.aarch64-linux-gnu.tar.gz"
[[ngspice]]
arch = "aarch64"
git-tree-sha1 = "bb8f71da65cd383a28289bc9cb929b13370512d3"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "d97cde26cbcebdea7246e47632b9624290cbd0717a4bb468b2b8fe4a6faa26b7"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.aarch64-linux-musl.tar.gz"
[[ngspice]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "175ed1aa1c47d9a6f91be4e4d47a6f6d054e23de"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "701922c0df71805d9987518b186ff32b157782c1622ac3a294885af582f3a134"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.armv6l-linux-gnueabihf.tar.gz"
[[ngspice]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2fab76b4f16b46f8ed515ff02a213c89e313d6c1"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "1d4c79c5fac644ca86045381bccf28353ad58ae77617d39659f4fce2d930ad64"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.armv6l-linux-musleabihf.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e46bd45ac295571c8e48ed53a7d1a1491ee5aae4"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "938e74a5feaac5d720f2e117ce8a767aa4971b9ee01c84b0f330e2447844b42b"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ngspice]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e43320726f1b90a8010bfa2897c8d87895f74ee9"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "c6c7618c41f980b34dfd9d0fbd68f2f41ebfb9addbd6ded8f2eec41831300b8f"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.armv7l-linux-musleabihf.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "ff2e45d9271b55f3ac9dc3422c1b3ecbc298775e"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "97f602386c38c018b6bc316ac3bc932521083bee63f4b118c5952510fabaede8"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.i686-linux-gnu.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "4b7d88e458ac324864fa58be2e897124fe04bbd0"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "9cff62fd75bfc25671eb36ecbde759bf43120fc6f1ca06cb6aced635374f8afe"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.i686-linux-musl.tar.gz"
[[ngspice]]
arch = "i686"
git-tree-sha1 = "3da5afc6127a61c8abb533977b6c46b406f96985"
os = "windows"

    [[ngspice.download]]
    sha256 = "2b5e809b3a0b790eb5f70702874bde1f9bd49f7d1fb2475d8d441fd5c255606b"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.i686-w64-mingw32.tar.gz"
[[ngspice]]
arch = "powerpc64le"
git-tree-sha1 = "651765922554c55382e6525ff8ccb16ece832ac9"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "5a783f65bde234272201f3670546052cc985bb70a2f6aa1dfb9ea643f939d219"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.powerpc64le-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "bb7b2eab6bdc9a8a97785071f5aacebed6351428"
os = "macos"

    [[ngspice.download]]
    sha256 = "8472584973aba2a6500de5af58a48292334094ad961dd924b3b6db361d6a3430"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.x86_64-apple-darwin.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "35a56baff42d69c664e87e87d11509c03e56c3d2"
libc = "glibc"
os = "linux"

    [[ngspice.download]]
    sha256 = "8c02e8b49bcdaf9c293c51c3ece69ebc56dfe343cc3f4861e62f233e9ca58de2"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.x86_64-linux-gnu.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "00a3e782e3b4349df8e53648aa149eaef3dc3ca1"
libc = "musl"
os = "linux"

    [[ngspice.download]]
    sha256 = "bfaa05082386f6738978477a0fbf49b0adf4b77adf42613b209a802d6e540f50"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.x86_64-linux-musl.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "226eeda7b1d1308de581725f8d4b279f1ce6cd83"
os = "freebsd"

    [[ngspice.download]]
    sha256 = "9daddc4f6d1fdf80c91b9de3bc534069f44354b6598e85e0b31cc9d291d02381"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.x86_64-unknown-freebsd.tar.gz"
[[ngspice]]
arch = "x86_64"
git-tree-sha1 = "67491a52f6263f8a0f271b776fa9d2ef5d41831c"
os = "windows"

    [[ngspice.download]]
    sha256 = "a347568d58b5fbf97dde35a4e5787fc0dcde4c628f68d61b4a2a30f6f57a0a5d"
    url = "https://github.com/JuliaBinaryWrappers/ngspice_jll.jl/releases/download/ngspice-v36.0.0+0/ngspice.v36.0.0.x86_64-w64-mingw32.tar.gz"
