# Autogenerated wrapper script for ngspice_jll for aarch64-apple-darwin
export libngspice, ngspice

JLLWrappers.@generate_wrapper_header("ngspice")
JLLWrappers.@declare_library_product(libngspice, "@rpath/libngspice.0.dylib")
JLLWrappers.@declare_executable_product(ngspice)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libngspice,
        "lib/libngspice.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ngspice,
        "bin/ngspice",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
