# Autogenerated wrapper script for ngspice_jll for i686-linux-gnu
export libngspice, ngspice

JLLWrappers.@generate_wrapper_header("ngspice")
JLLWrappers.@declare_library_product(libngspice, "libngspice.so.0")
JLLWrappers.@declare_executable_product(ngspice)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libngspice,
        "lib/libngspice.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ngspice,
        "bin/ngspice",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
